### ISSUE TITLE
'(cid:#)' occurences in simple_pdf_to_txt( ) raw text (produced by the 'pdf2txt.py' program)

### ISSUE THREAD

**Issue by ckaraneen** [eellak/gsoc2018-GG-extraction#1]
Due to specific Adobe formatting, pervading meaningful text in older (mostly pre-2006) GG issues.

E.g. ... "(cid:655)(cid:635)(cid:654)" ... "(cid:3)" ...

**Comment by ckaraneen** [comment]
Possible solutions: 
1. Research and manually fix
2. Use different converter

**Comment by papachristoumarios** [comment]
Hello,
Is there any workaround for that?

**Comment by ckaraneen** [comment]
Hello,

After some rough googling this seems to sum up some solutions, although not that simple:

https://stackoverflow.com/questions/3488042/how-can-i-extract-embedded-fonts-from-a-pdf-as-valid-font-files`

**Comment by papachristoumarios** [comment]
You can also perform ocr (a bit slow but working for clean documents)
I have made a tool that does this in my repository ellak/gsoc2018-3gm under
scripts/ocr.py using tesseract. Slow but working for newer documents (post
2000).

**Comment by ckaraneen** [comment]
I will check it out,

Thanks!

**Comment by ckaraneen** [comment]
Skip cid occurences.

Closing for now.
